on: [push]
jobs:
  test:
    name: 🧪 test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml
      - name: Run tests
        run: |
          npm install
          npm run test
  check:
    name: ✅ check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run checks
        run: |
          npm install
          npm run check
