on: [push]
jobs:
  test:
    name: 🧪 test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: start docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml
      - run: cp .env.example .env
      - name: setup env
        uses: xom9ikk/dotenv@v2.3.0
      - run: npm install
      - run: npm run migrate
      - run: npm run test
  check:
    name: ✅ check
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run check
